# Generated by Django 2.2.6 on 2019-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
