# Generated by Django 2.2.5 on 2019-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
