# Generated by Django 2.2.5 on 2019-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_posts_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
