# Generated by Django 2.2.5 on 2019-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_auto_20191007_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
