# Generated by Django 2.2.5 on 2019-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0006_auto_20191007_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.CharField(default=None, editable=False, max_length=200),
        ),
    ]
