# Generated by Django 2.2.5 on 2019-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0008_auto_20191007_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
