# Generated by Django 2.2.6 on 2019-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0010_auto_20191110_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes_post',
            name='number_like',
            field=models.IntegerField(default=0),
        ),
    ]
