# Generated by Django 2.2.6 on 2019-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0011_likes_post_number_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes_post',
            old_name='user',
            new_name='like_user',
        ),
        migrations.RemoveField(
            model_name='likes_post',
            name='number_like',
        ),
        migrations.AddField(
            model_name='posts',
            name='number_likes',
            field=models.IntegerField(default=0),
        ),
    ]
