# Generated by Django 2.2.6 on 2019-12-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0012_auto_20191110_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='likes_post',
            options={'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='likes_post',
            table=None,
        ),
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
