# Generated by Django 2.2.5 on 2019-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('post_likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
