# Generated by Django 2.2.5 on 2019-11-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Posts'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
