# Generated by Django 2.2.5 on 2019-11-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20191102_2109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
