# Generated by Django 2.2.6 on 2019-11-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20191102_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
